export const categories: string[] = [
  'Actors',
  'Animals',
  'Bands',
  'Board Games',
  'Body Parts',
  'Book Titles',
  'Brands',
  'Cartoons',
  'Cities',
  'Clothing',
  'Colors',
  'Countries',
  'Drinks',
  'Fictional Characters',
  'Foods',
  'Historical Figures',
  'Hobbies',
  'Jobs',
  'Landmarks',
  'Languages',
  'Movies',
  'Musicians',
  'Mythical Creatures',
  'Plants',
  'Snack Foods',
  'Song Titles',
  'Sports Stars',
  'Sports',
  'Superheroes',
  'TV Shows',
  'Things That Are Round',
  'Things You Find at the Beach',
  'Things You Find in a Car',
  'Things You Find in a Garage',
  'Things You Find in a Kitchen',
  'Things You Find in a School',
  'Video Games',
  'Villains',
  'Weather',
  '6 Letter Words',
  '7 Letter Words',
  '8 Letter Words',
];
